-- Plantilla: perfiles sin Supabase Auth (migración 20260417170000).
-- `id` = gen_random_uuid(); login vía app_login_simple + password_hash.
--
-- INSERT INTO public.profiles (id, country_code, role, employee_number, display_name, catalog_segment)
-- VALUES (
--   gen_random_uuid(),
--   'PC',
--   'editor',
--   NULL,
--   'Mi Sucursal',
--   'top25'
-- );
--
-- SELECT public.set_profile_password('Mi Sucursal', 'Pintacomex2k');
